@baseUrl = http://localhost:6969
### Run instances
POST {{baseUrl}}/run_instances
Content-Type: application/json

{
    "name": "meow"
}

### Describe Instances
GET {{baseUrl}}/describe_instances

### Stop Instances
POST {{baseUrl}}/stop_instances
Content-Type: application/json

{
    "instance_id": "09f852831cd2"
}

### Terminate Instances
POST {{baseUrl}}/terminate_instances
Content-Type: application/json

{
    "instance_id": "09f852831cd2"
}

### List Volumes
GET {{baseUrl}}/list_volumes
Content-Type: application/json

### delete volumes
DELETE {{baseUrl}}/remove_volume
Content-Type: application/json

{
    "name": "meow2_data"
}
