@baseUrl = http://localhost:6969
### Run instances
POST {{baseUrl}}/run_instances
Content-Type: application/json

{
    "name": "server2",
    "ssh_port": 6768,
    "mem": 2048,
    "cpus": 2
}

### Describe Instances
GET {{baseUrl}}/describe_instances

### Terminate Instances
POST {{baseUrl}}/terminate_instances
Content-Type: application/json

{
    "instance_id": "f75c6b0075da"
}

### List Volumes
GET {{baseUrl}}/list_volumes
Content-Type: application/json

### delete volumes
DELETE {{baseUrl}}/remove_volume
Content-Type: application/json

{
    "name": "meow2_data"
}
